
# WINDOW SETTINGS
WINDOW_SIZE = (1920, 1080)
WINDOW_TITLE = "Animal Ambush"
FPS = 60


# WIN SETTINGS
WIN_SIZE = [480, 270]
WIN_SCALE_FACTOR = 4


# CAMERA SETTINGS
CAMERA_ORIGIN = (int(WIN_SIZE[0]/2), int(WIN_SIZE[1]/2))
CAMERA_ROTATION_MULTIPLIER = 0.2
CAMERA_ZOOM_MULTIPLIER = 1.2
CAMERA_ZOOM_MAX = 3
CAMERA_SELECT_DISTANCE_THRESHOLD = 10
CAMERA_SELECT_DISTANCE = 50


# OBJECT SETTINGS
OBJECT_HOVER_SPEED = 10
OBJECT_HOVER_HEIGHT = 10
OBJECT_HOVER_THRESHOLD = 0.01


# TROOP SETTINGS
TROOP_MOVEMENT_FRAMES = 10


# GAME SETTINGS
GAME_BACKGROUND_COLOUR = (174,226,255)


# STACK SETTINGS
STACK_CACHE_ENABLED = False
STACK_FILENAME = "spritestacks"
STACK_CACHE_FILENAME = "cache"
STACK_LAYER_GAP = 2
STACK_LEVEL_HEIGHT =  5 * STACK_LAYER_GAP
STACK_SCALE_FACTOR = 3
STACK_INITIAL_ROTATION = -90
STACK_DEGREE_GAP = 5


# FULL QUALITY MODIFICATIONS
STACK_CACHE_ENABLED = True
FPS = 60
WIN_SIZE = [1920, 1080]
WIN_SCALE_FACTOR = 1
STACK_SCALE_FACTOR = 3*3
STACK_LAYER_GAP = 2*4

CAMERA_ORIGIN = (int(WIN_SIZE[0]/2), int(WIN_SIZE[1]/2))
STACK_LEVEL_HEIGHT =  5 * STACK_LAYER_GAP


# LOADING SETTINGS
LOADING_BAR_BACKGROUND_COLOUR = (174,226,255)
LOADING_BAR_COLOUR = (255,255,255)
LOADING_BAR_MARGINS = int(WIN_SIZE[0]/20)
LOADING_BAR_HEIGHT = int(WIN_SIZE[0]/50)
LOADING_BAR_BOX = [LOADING_BAR_MARGINS, WIN_SIZE[1]-LOADING_BAR_MARGINS-LOADING_BAR_HEIGHT, WIN_SIZE[0]-2*LOADING_BAR_MARGINS, LOADING_BAR_HEIGHT]


# LEVEL SETTINGS
LEVEL_ALPHA = (0,0,0,0)
LEVEL_GROUND_COLOUR0 = (171, 221, 100)
LEVEL_GROUND_COLOUR1 = (107, 201, 108)
LEVEL_BORDER_COLOUR0 = (201, 115, 115)
LEVEL_BORDER_COLOUR1 = (116, 85, 95)
LEVEL_STACK_HEIGHT = 6
LEVEL_TILE_SIZE = 8
LEVEL_GROOVE_DISTANCE = 1


